TERM_PROGRAM=vscode
TERM=xterm-256color
SHELL=/bin/bash
TMPDIR=/var/folders/zz/zyxvpxvq6csfxvn_n000chnr00345f/T/
Apple_PubSub_Socket_Render=/private/tmp/com.apple.launchd.z8HI18KFwP/Render
TERM_PROGRAM_VERSION=1.79.2
ORIGINAL_XDG_CURRENT_DESKTOP=undefined
MallocNanoZone=0
USER=marihovh
SSH_AUTH_SOCK=/private/tmp/com.apple.launchd.jEUdGP6bSI/Listeners
__CF_USER_TEXT_ENCODING=0x190AE:0x0:0x0
PATH=/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/munki
PWD=/Users/marihovh/Desktop/minishell
LANG=en_US.UTF-8
VSCODE_GIT_ASKPASS_EXTRA_ARGS=--ms-enable-electron-run-as-node
XPC_FLAGS=0x0
XPC_SERVICE_NAME=0
SHLVL=2
HOME=/Users/marihovh
VSCODE_GIT_ASKPASS_MAIN=/private/var/folders/zz/zyxvpxvq6csfxvn_n000chnr00345f/T/AppTranslocation/BD346028-3F99-4AEA-A5F6-E73EB549E3BD/d/Visual Studio Code.app/Contents/Resources/app/extensions/git/dist/askpass-main.js
LOGNAME=marihovh
VSCODE_GIT_IPC_HANDLE=/var/folders/zz/zyxvpxvq6csfxvn_n000chnr00345f/T/vscode-git-afb7c521fc.sock
VSCODE_GIT_ASKPASS_NODE=/private/var/folders/zz/zyxvpxvq6csfxvn_n000chnr00345f/T/AppTranslocation/BD346028-3F99-4AEA-A5F6-E73EB549E3BD/d/Visual Studio Code.app/Contents/Frameworks/Code Helper (Plugin).app/Contents/MacOS/Code Helper (Plugin)
GIT_ASKPASS=/private/var/folders/zz/zyxvpxvq6csfxvn_n000chnr00345f/T/AppTranslocation/BD346028-3F99-4AEA-A5F6-E73EB549E3BD/d/Visual Studio Code.app/Contents/Resources/app/extensions/git/dist/askpass.sh
COLORTERM=truecolor
_=./minishell
shyshell$ exit
